[window]
padding = { x = 4, y = 4 }

[font]
size = 13

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '0x111111'
foreground = '0xeeffff'

[colors.cursor]
text = '0x212121'
cursor = '0xeeffff'

[colors.normal]
black = '0x212121'
red = '0xf07178'
green = '0xc3e88d'
yellow = '0xffcb6b'
blue = '0x82aaff'
magenta = '0xc792ea'
cyan = '0x89ddff'
white = '0xeeffff'

[colors.bright]
black = '0x4a4a4a'
red = '0xf78c6c'
green = '0x303030'
yellow = '0x353535'
blue = '0xb2ccd6'
magenta = '0xeeffff'
cyan = '0xff5370'
white = '0xffffff'
