-- local coq_setup, coq = pcall(require, "coq")
-- if not coq_setup then
-- 	return
-- end

-- vim.g.coq_settings = {
-- 	-- auto_start = "shut-up",
-- 	xdg = true,
-- 	display = {
-- 		ghost_text = {
-- 			enabled = false,
-- 		},
-- 		preview = {
-- 			border = "rounded",
-- 		},
-- 		pum = {
-- 			fast_close = false,
-- 		},
-- 	},
-- 	completion = {
-- 		always = true,
-- 	},
-- 	keymap = {
-- 		recommended = false,
-- 	}
-- }

-- vim.cmd('COQnow --shut-up')
