call plug#begin ('~/.local/share/.vim/plugged')

" Git wrapper.
Plug 'tpope/vim-fugitive'

" Comment stuff easily.
Plug 'preservim/nerdcommenter'

" Better syntax highlight.
Plug 'sheerun/vim-polyglot'

"Colorscheme.
Plug 'sainnhe/gruvbox-material'

" PEP8 Formatter.
Plug 'google/yapf', {'rtp': 'plugins/vim', 'for': 'python'}

call plug#end ()

" Load plugin and indentation for each detected file type.
filetype plugin indent on

" Fixes the cursors
let &t_SI = "\e[6 q"
let &t_SR = "\e[4 q"
let &t_EI = "\e[2 q"
norm i

" Will improve gf and find command.
set path+=**

" Had problems without it.
set encoding=utf-8

" Increase command history.
let history=10000

" Uses syntax highlight that respect my settings.
syntax enable

" Allows me to move to another buffer without writing to the old file before.
set hidden

" Number column.
set number

" Ruler on the statusline.
set ruler

" Insert and remove 4 spaces when pressed tab, shifted or pressed BS.
set shiftwidth=4 tabstop=4 softtabstop=4 expandtab smarttab

" Copy the identation from the line form the above or indent when needed.
set autoindent smartindent

" Backspace deletes indents and tabs.
set backspace="indent,eol,start"

" Incremental search with highlight and only case-sensitive when a uppercase letter has been inserted.
set hls incsearch smartcase ignorecase
 
" Basic statusline.
set laststatus=2

" Update file within vim if it has been changed from outside.
set autoread

" Autocompletion enabled menu.
set wildmenu

" More room to command window.
set cmdheight=2

" For my mental sanity.
set noerrorbells

" Enable true color support.
set termguicolors

" Enable mouse support.
set mouse=a

" Colorcheme configuration.
set background=dark
let g:gruvbox_material_background = 'hard'
let g:gruvbox_material_sign_column_background = 'none'
let g:gruvbox_material_enable_italic = 1
let g:gruvbox_material_transparent_background = 1
let g:gruvbox_material_better_performance = 1
colorscheme gruvbox-material

" Keyboard mappings.
let mapleader = " "

nnoremap <silent> <leader>q :cw<CR>
nnoremap <silent> <leader>Q :ccl<CR>
nnoremap <silent> <C-n>     :cnext<CR>
nnoremap <silent> <C-p>     :cprev<CR>

"This unsets the last search pattern register when hitting return.
nnoremap <silent> <CR> :nohlsearch<CR>

" Statusline
set noshowmode

let g:currentMode={
      \ 'n'          :'NORMAL',
      \ 'no'         :"OPERATOR PENDING",
      \ 'nov'        :"OPERATOR PENDING",
      \ 'noV'        :"OPERATOR PENDING",
      \ 'no"\<C-v>"' :"OPERATOR PENDING",
      \ 'niI'        :'NORMAL',
      \ 'niR'        :'NORMAL',
      \ 'niV'        :'NORMAL',
      \ 'v'          :'VISUAL',
      \ 'V'          :"V-LINE",
      \ "\<C-v>"     :"V-BLOCK",
      \ 's'          :'SELECT',
      \ 'S'          :"S-LINE",
      \ "\<C-s>"     :"S-BLOCK",
      \ 'i'          :'INSERT',
      \ 'ic'         :'INSERT',
      \ 'ix'         :'INSERT',
      \ 'R'          :'REPLACE',
      \ 'Rc'         :'REPLACE',
      \ 'Rv'         :"V-REPLACE",
      \ 'Rx'         :'REPLACE',
      \ 'c'          :'COMMAND',
      \ 'cv'         :'EX MODE',
      \ 'ce'         :'EX MODE',
      \ 'r'          :'PROMPT',
      \ 'rm'         :'MORE',
      \ 'r?'         :'CONFIRM',
      \ '!'          :'SHELL',
      \ 't'          :'TERMINAL',
      \}

highlight TabLineSel gui=bold cterm=bold

let g:gitBranch = ''

augroup UPDATE_GITBRANCH
    autocmd!
    autocmd BufEnter * :call UpdateGitBranch()
    autocmd ShellCmdPost * :call UpdateGitBranch()
augroup END

function! UpdateGitBranch ()
    if (system ("git rev-parse --is-inside-work-tree 2>/dev/null | tr -d '\n'") == "true")
        let g:gitBranch = system ("git branch --show-current 2>/dev/null | tr -d '\n'")
        set statusline=%#TabLineSel#
        set statusline+=\ %{g:currentMode[mode()]}
        set statusline+=\ %#TabLine#
        set statusline+=\ %{g:gitBranch}
        set statusline+=\ %#StatusLineNC#
        set statusline+=\ %F\ %m\ %r
        set statusline+=\ %=
        set statusline+=\ %#TabLine#
        set statusline+=\ %{&fileencoding?&fileencoding:&encoding}/%{&fileformat}\ %y
        set statusline+=\ %#TabLineSel#
        set statusline+=\ %P\ %l:%c
        set statusline+=\ 
    else
        set statusline=%#TabLineSel#
        set statusline+=\ %{g:currentMode[mode()]}
        set statusline+=\ %#StatusLineNC#
        set statusline+=\ %F\ %m\ %r
        set statusline+=\ %=
        set statusline+=\ %#TabLine#
        set statusline+=\ %{&fileencoding?&fileencoding:&encoding}/%{&fileformat}\ %y
        set statusline+=\ %#TabLineSel#
        set statusline+=\ %P\ %l:%c
        set statusline+=\ 
    endif
endfunction
